import Checklist from "./checklist";
import Todo from "./todos";

enum ProjectIcon {
    List = "format_list_bulleted",
    Event = "event",
    Alarm = "alarm",
    Time = "access_time",
    Bookmark = "bookmark",
    Location = "location_on",
    Gift = "card_giftcard",
    Cake = "cake",
    School = "school",
    File = "insert_drive_file",
    Library = "local_library",
    CreditCard = "credit_card",
    Bank = "account_balance",
    Money = "attach_money",
    Jogger = "directions_run",
    Food = "local_dining",
    Bar = "local_bar",
    Breakfast = "free_breakfast",
    Phone = "phone",
    Medical = "healing",
    Hospital = "local_hospital",
    Business = "business",
    Suitcase = "business_center",
    Code = "code",
    Law = "gavel",
    Store = "store",
    Shop = "shopping_cart",
    Spa = "spa",
    Shipping = "local_shipping",
    Sleep = "hotel",
    Group = "group",
    Child = "child_care",
    Baby = "child_friendly",
    Pet = "pets",
    Brush = "brush",
    Beach = "beach_access",
    Bike = "directions_bike",
    Boat = "directions_boat",
    Bus = "directions_bus",
    Car = "directions_car",
    Train = "directions_subway",
    Plane = "flight",
    Announcement = "announcement",
    Assignment = "assignment",
    Golf = "golf_course",
    Movies = "local_movies",
    Games = "games",
    Video = "personal_video",
    Music = "music_note",
    Heart = "favorite",
    Star = "star",
}

export default interface Project extends Checklist<Todo> {
    title: string,
    icon: ProjectIcon,
}